//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyNSIS.Resources {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyNSIS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? "";
        public static string AppTitle_New => ResourceManager.GetString("AppTitle_New", resourceCulture) ?? "";
        public static string AppTitle_Format => ResourceManager.GetString("AppTitle_Format", resourceCulture) ?? "";
        public static string AppSubtitle => ResourceManager.GetString("AppSubtitle", resourceCulture) ?? "";
        public static string Btn_AboutLicenses => ResourceManager.GetString("Btn_AboutLicenses", resourceCulture) ?? "";

        // Tabs
        public static string Tab_BasicInfo => ResourceManager.GetString("Tab_BasicInfo", resourceCulture) ?? "";
        public static string Tab_SourceFolder => ResourceManager.GetString("Tab_SourceFolder", resourceCulture) ?? "";
        public static string Tab_InstallDestination => ResourceManager.GetString("Tab_InstallDestination", resourceCulture) ?? "";
        public static string Tab_Shortcuts => ResourceManager.GetString("Tab_Shortcuts", resourceCulture) ?? "";
        public static string Tab_License => ResourceManager.GetString("Tab_License", resourceCulture) ?? "";
        public static string Tab_Output => ResourceManager.GetString("Tab_Output", resourceCulture) ?? "";
        public static string Tab_SaveLoad => ResourceManager.GetString("Tab_SaveLoad", resourceCulture) ?? "";
        public static string Tab_PostInstall => ResourceManager.GetString("Tab_PostInstall", resourceCulture) ?? "";

        // Basic Info
        public static string Section_ApplicationDetails => ResourceManager.GetString("Section_ApplicationDetails", resourceCulture) ?? "";
        public static string Section_RegistrationMode => ResourceManager.GetString("Section_RegistrationMode", resourceCulture) ?? "";
        public static string Radio_RegisterToAppsAndFeatures => ResourceManager.GetString("Radio_RegisterToAppsAndFeatures", resourceCulture) ?? "";
        public static string Radio_NoRegistry => ResourceManager.GetString("Radio_NoRegistry", resourceCulture) ?? "";
        public static string Label_NoRegistryWarning => ResourceManager.GetString("Label_NoRegistryWarning", resourceCulture) ?? "";
        public static string Label_CompanyName => ResourceManager.GetString("Label_CompanyName", resourceCulture) ?? "";
        public static string Label_ApplicationName => ResourceManager.GetString("Label_ApplicationName", resourceCulture) ?? "";
        public static string Label_Version => ResourceManager.GetString("Label_Version", resourceCulture) ?? "";
        public static string Label_Language => ResourceManager.GetString("Label_Language", resourceCulture) ?? "";
        public static string Label_UseLocale => ResourceManager.GetString("Label_UseLocale", resourceCulture) ?? "";
        public static string Label_FixedLanguage => ResourceManager.GetString("Label_FixedLanguage", resourceCulture) ?? "";
        public static string Label_InstallerIcon => ResourceManager.GetString("Label_InstallerIcon", resourceCulture) ?? "";

        // Source Folder
        public static string Label_SourceFolderPath => ResourceManager.GetString("Label_SourceFolderPath", resourceCulture) ?? "";
        public static string Label_SourceFolderDescription => ResourceManager.GetString("Label_SourceFolderDescription", resourceCulture) ?? "";

        // Install Destination
        public static string Label_InstallDestination => ResourceManager.GetString("Label_InstallDestination", resourceCulture) ?? "";
        public static string Radio_AppDataRoaming => ResourceManager.GetString("Radio_AppDataRoaming", resourceCulture) ?? "";
        public static string Radio_AppDataLocal => ResourceManager.GetString("Radio_AppDataLocal", resourceCulture) ?? "";
        public static string Radio_ProgramFiles => ResourceManager.GetString("Radio_ProgramFiles", resourceCulture) ?? "";
        public static string Radio_Custom => ResourceManager.GetString("Radio_Custom", resourceCulture) ?? "";
        public static string Label_AllowUserChange => ResourceManager.GetString("Label_AllowUserChange", resourceCulture) ?? "";

        // Shortcuts
        public static string Label_DesktopShortcuts => ResourceManager.GetString("Label_DesktopShortcuts", resourceCulture) ?? "";
        public static string Label_StartMenuShortcuts => ResourceManager.GetString("Label_StartMenuShortcuts", resourceCulture) ?? "";
        public static string Header_Type => ResourceManager.GetString("Header_Type", resourceCulture) ?? "";
        public static string Header_Path => ResourceManager.GetString("Header_Path", resourceCulture) ?? "";
        public static string Btn_AddFile => ResourceManager.GetString("Btn_AddFile", resourceCulture) ?? "";
        public static string Btn_AddFolder => ResourceManager.GetString("Btn_AddFolder", resourceCulture) ?? "";
        public static string Btn_Remove => ResourceManager.GetString("Btn_Remove", resourceCulture) ?? "";

        // License
        public static string Label_LicenseType => ResourceManager.GetString("Label_LicenseType", resourceCulture) ?? "";
        public static string Radio_LicenseDefault => ResourceManager.GetString("Radio_LicenseDefault", resourceCulture) ?? "";
        public static string Radio_LicenseFile => ResourceManager.GetString("Radio_LicenseFile", resourceCulture) ?? "";
        public static string Radio_LicenseText => ResourceManager.GetString("Radio_LicenseText", resourceCulture) ?? "";

        // Output
        public static string Label_OutputFolder => ResourceManager.GetString("Label_OutputFolder", resourceCulture) ?? "";
        public static string Label_CleanupType => ResourceManager.GetString("Label_CleanupType", resourceCulture) ?? "";
        public static string Radio_CleanupAll => ResourceManager.GetString("Radio_CleanupAll", resourceCulture) ?? "";
        public static string Radio_CleanupPreserve => ResourceManager.GetString("Radio_CleanupPreserve", resourceCulture) ?? "";

        // Save/Load
        public static string Label_ConfigFile => ResourceManager.GetString("Label_ConfigFile", resourceCulture) ?? "";
        public static string Desc_SaveLoadConfig => ResourceManager.GetString("Desc_SaveLoadConfig", resourceCulture) ?? "";
        public static string Btn_Save => ResourceManager.GetString("Btn_Save", resourceCulture) ?? "";
        public static string Btn_Load => ResourceManager.GetString("Btn_Load", resourceCulture) ?? "";
        public static string Btn_SaveAs => ResourceManager.GetString("Btn_SaveAs", resourceCulture) ?? "";

        // Buttons
        public static string Btn_Browse => ResourceManager.GetString("Btn_Browse", resourceCulture) ?? "";
        public static string Btn_Build => ResourceManager.GetString("Btn_Build", resourceCulture) ?? "";
        public static string Btn_Interrupt => ResourceManager.GetString("Btn_Interrupt", resourceCulture) ?? "";
        public static string Btn_OK => ResourceManager.GetString("Btn_OK", resourceCulture) ?? "";
        public static string Btn_Cancel => ResourceManager.GetString("Btn_Cancel", resourceCulture) ?? "";
        public static string Btn_OpenOutputFolder => ResourceManager.GetString("Btn_OpenOutputFolder", resourceCulture) ?? "";
        public static string Btn_OpenFolder => ResourceManager.GetString("Btn_OpenFolder", resourceCulture) ?? "";
        public static string Btn_Close => ResourceManager.GetString("Btn_Close", resourceCulture) ?? "";

        // Messages
        public static string Msg_BuildCompleted => ResourceManager.GetString("Msg_BuildCompleted", resourceCulture) ?? "";
        public static string Msg_Building => ResourceManager.GetString("Msg_Building", resourceCulture) ?? "";
        public static string Msg_BuildSuccess => ResourceManager.GetString("Msg_BuildSuccess", resourceCulture) ?? "";
        public static string Msg_BuildFailed => ResourceManager.GetString("Msg_BuildFailed", resourceCulture) ?? "";
        public static string Msg_BuildCancelled => ResourceManager.GetString("Msg_BuildCancelled", resourceCulture) ?? "";
        public static string Msg_UnsavedChanges => ResourceManager.GetString("Msg_UnsavedChanges", resourceCulture) ?? "";
        public static string Msg_UnsavedTitle => ResourceManager.GetString("Msg_UnsavedTitle", resourceCulture) ?? "";
        public static string Msg_SaveAndExit => ResourceManager.GetString("Msg_SaveAndExit", resourceCulture) ?? "";
        public static string Msg_ExitWithoutSaving => ResourceManager.GetString("Msg_ExitWithoutSaving", resourceCulture) ?? "";
        public static string Msg_BuildInProgress => ResourceManager.GetString("Msg_BuildInProgress", resourceCulture) ?? "";
        public static string Msg_AlreadyRunning => ResourceManager.GetString("Msg_AlreadyRunning", resourceCulture) ?? "";
        public static string Msg_ConfigLoaded => ResourceManager.GetString("Msg_ConfigLoaded", resourceCulture) ?? "";
        public static string Msg_ConfigSaved => ResourceManager.GetString("Msg_ConfigSaved", resourceCulture) ?? "";

        // Errors
        public static string Err_RequiredField => ResourceManager.GetString("Err_RequiredField", resourceCulture) ?? "";
        public static string Err_InvalidVersion => ResourceManager.GetString("Err_InvalidVersion", resourceCulture) ?? "";
        public static string Err_InvalidPath => ResourceManager.GetString("Err_InvalidPath", resourceCulture) ?? "";
        public static string Err_InvalidPathEnding => ResourceManager.GetString("Err_InvalidPathEnding", resourceCulture) ?? "";
        public static string Err_InvalidNameEnding => ResourceManager.GetString("Err_InvalidNameEnding", resourceCulture) ?? "";
        public static string Err_NameTooLong => ResourceManager.GetString("Err_NameTooLong", resourceCulture) ?? "";
        public static string Err_UncPathNotAllowed => ResourceManager.GetString("Err_UncPathNotAllowed", resourceCulture) ?? "";
        public static string Err_PathNotFound => ResourceManager.GetString("Err_PathNotFound", resourceCulture) ?? "";
        public static string Err_FileNotFound => ResourceManager.GetString("Err_FileNotFound", resourceCulture) ?? "";
        public static string Err_FolderNotFound => ResourceManager.GetString("Err_FolderNotFound", resourceCulture) ?? "";
        public static string Err_InvalidIconFormat => ResourceManager.GetString("Err_InvalidIconFormat", resourceCulture) ?? "";
        public static string Err_ShortcutTargetNotFound => ResourceManager.GetString("Err_ShortcutTargetNotFound", resourceCulture) ?? "";
        public static string Err_NsisNotFound => ResourceManager.GetString("Err_NsisNotFound", resourceCulture) ?? "";
        public static string Err_NsisVersionMismatch => ResourceManager.GetString("Err_NsisVersionMismatch", resourceCulture) ?? "";
        public static string Err_NsisValidationFailed => ResourceManager.GetString("Err_NsisValidationFailed", resourceCulture) ?? "";
        public static string Err_ValidationFailed => ResourceManager.GetString("Err_ValidationFailed", resourceCulture) ?? "";
        public static string Err_LoadConfigFailed => ResourceManager.GetString("Err_LoadConfigFailed", resourceCulture) ?? "";
        public static string Err_SaveConfigFailed => ResourceManager.GetString("Err_SaveConfigFailed", resourceCulture) ?? "";
        public static string Err_ReservedFileName => ResourceManager.GetString("Err_ReservedFileName", resourceCulture) ?? "";
        public static string Err_InvalidExecutableFormat => ResourceManager.GetString("Err_InvalidExecutableFormat", resourceCulture) ?? "";

        // PostInstall
        public static string Section_PostInstallActions => ResourceManager.GetString("Section_PostInstallActions", resourceCulture) ?? "";
        public static string Label_OpenInstallFolder => ResourceManager.GetString("Label_OpenInstallFolder", resourceCulture) ?? "";
        public static string Label_RunAfterInstall => ResourceManager.GetString("Label_RunAfterInstall", resourceCulture) ?? "";
        public static string Label_RunAfterInstallPath => ResourceManager.GetString("Label_RunAfterInstallPath", resourceCulture) ?? "";
        public static string Desc_RunAfterInstall => ResourceManager.GetString("Desc_RunAfterInstall", resourceCulture) ?? "";

        // Dialog Filters
        public static string Filter_XmlFiles => ResourceManager.GetString("Filter_XmlFiles", resourceCulture) ?? "";
        public static string Filter_ExecutableFiles => ResourceManager.GetString("Filter_ExecutableFiles", resourceCulture) ?? "";
        public static string Filter_IcoFiles => ResourceManager.GetString("Filter_IcoFiles", resourceCulture) ?? "";
        public static string Filter_TxtFiles => ResourceManager.GetString("Filter_TxtFiles", resourceCulture) ?? "";
        public static string Filter_AllFiles => ResourceManager.GetString("Filter_AllFiles", resourceCulture) ?? "";
    }
}
